site_name: Cocktail Maker Documentation
site_description: A Python application for cocktail recipe management
site_author: Lee Dongju
# site_url: https://yourdomain.com/cocktail-maker/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.annotate
    - content.code.copy

nav:
  - Home: index.md
  - "User Guide": user-guide.md
  - "API Reference": api-reference.md
  - About: about.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_bases: true
            show_root_full_path: false
            docstring_options:
              ignore_init_summary: true
            members_order: source
            filters:
              - "!^_"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dongju93/cocktail-maker
