services:
  cocktail-maker:
    image: cocktail-maker:0.1.1
    container_name: cocktail-maker
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - cocktail_maker_network

networks:
  cocktail_maker_network:
    external: true
    name: cocktail_maker_main_network
