services:
  cocktail-maker:
    image: cocktail-maker:0.1.3
    hostname: "instance-{{.Task.Slot}}"
    domainname: "cocktail-maker.local"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://127.0.0.1:8000/api/v1/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - cocktail_maker_network_swarm
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - cocktail_maker_network_swarm
    depends_on:
      - cocktail-maker
    command: /bin/sh -c "sleep 30 && nginx -g 'daemon off;'"
    deploy:
      replicas: 1

networks:
  cocktail_maker_network_swarm:

configs:
  nginx_config:
    file: ./nginx.conf
