services:
  cocktail-maker:
    image: cocktail-maker:0.1.3
    container_name: cocktail-maker
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8000/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - cocktail_maker_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - cocktail_maker_network

networks:
  cocktail_maker_network:
