services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - cocktail_maker_network

networks:
  cocktail_maker_network:
    external: true
    name: cocktail_maker_main_network