services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0.4-ubuntu2204
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env.development.local
    volumes:
      - type: bind
        source: /Volumes/Transcend/App/mongodb/data
        target: /data/db
        read_only: false
    networks:
      - cocktail_maker_main_network

  su-auth:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: supertokens
    ports:
      - "3567:3567"
    env_file:
      - .env.development.local
    environment:
      POSTGRESQL_HOST: "pg-auth"
      POSTGRESQL_PORT: "5432"
    depends_on:
      - pg-auth
    networks:
      - cocktail_maker_main_network
    sysctls:
      - net.ipv4.tcp_keepalive_time=60
      - net.ipv4.tcp_keepalive_intvl=5
      - net.ipv4.tcp_keepalive_probes=3

  pg-auth:
    image: postgres:18beta1
    container_name: postgres-auth
    ports:
      - "5433:5432"
    env_file:
      - .env.development.local
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      - cocktail_maker_main_network

networks:
  cocktail_maker_main_network:
volumes:
  postgres_data:
